function actor_on_first_update()
	if has_alife_info("agroprom_underground_drugkit_spawned") then return end

	printf("[agroprom_drugkit_spawner_gamma] Initialization..."){r%level:l03_agroprom}
	alife_create_item("itm_drugkit", {vector():set({w%x:110.3}, {w%y:-2.26}, {w%z:-21.6}), {w%lvid:8952}, {w%gvid:3727}})
	db.actor:give_info_portion("agroprom_underground_drugkit_spawned")
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update", actor_on_first_update)
end